version: '3'

services:

  db:
    image: postgres
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PORT=5432
    env_file:
      - ./env.dev.db
    volumes:
      - ./postgres-data/pgdata:/var/lib/postgresql/data/pgdata
    ports:
       - "5432:5432"

  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: >
      sh -c "gunicorn web.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - "8000"
    env_file:
      - ./env.dev
    volumes:
      - ./media:/home/app/web/media
      - ./migrations:/home/app/web/parambi/migrations
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./media:/home/app/web/media
    depends_on:
      - web